<?php
// Start the session
ini_set('session.gc_maxlifetime', 86400);
session_set_cookie_params(86400);
session_start();
// Check user login or not
// if(!isset($_SESSION["user"]) ||  $_SESSION['annotation_mode'] != 'evidence'){
//     include file_get_contents('index.php');
//     echo "<!--";
// }
// else if( $_SESSION['finished_calibration'] == 2 && $_SESSION['active'] <= 0){
//   echo 'Your calibration has not been evaluated yet. Please log into the <a href="http://mediawiki.feverous.co.uk/FEVEROUS/calibration_evaluation_evidence_user.php"> user evaluation interface</a> to continue or get in contact with your project coordinator.';
//   $_SESSION = array();
//   session_destroy();
//   echo "<!--";
// }else if( $_SESSION['finished_calibration'] == 1 && $_SESSION['calibration_score'] == 0){
//   echo 'Your calibration has not been evaluated yet. Please log into the <a href="http://mediawiki.feverous.co.uk/FEVEROUS/calibration_evaluation_evidence_user.php"> user evaluation interface</a> to continue.';
//   $_SESSION = array();
//   session_destroy();
//   echo "<!--";
// }
?>

<html>
<head>
  <link rel="stylesheet" href="css/style_evidence_annotation.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />


  <script src="js/extensions/jquery.js"></script>
  <script src="js/extensions/jquery.md5.js"></script>
  <script src="js/extensions/jquery_ui.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
  <script src="https://cdn.jsdelivr.net/gh/vast-engineering/jquery-popup-overlay@2/jquery.popupoverlay.min.js"></script>
  <script src="js/highlighter_test.js"></script>
  <script src="js/evidence_annotation.js"></script>

  <meta name="viewport" content="width=device-width"/>

</head>

<body style="font-family: sans-serif">

  <div class="topnav" id="myTopnav">
    <a href="user-details.php" id="user-details" class="fa fa-user-circle-o">User Details</a>
    <a href="annotation_guidelines/Evidence_annotation/evidence_guidelines_v1-72.pdf" class="fa fa-file-pdf-o" target="_blank">Annotation Guidelines</a>
    <a href="" class="logout fa fa-sign-out" style="text-align:right">Logout</a>
    <?php if ($_SESSION['finished_calibration'] !=2) echo '<a class="fa fa-exclamation" style="color:red; text-align:left"> CALIBRATION MODE. COMPLETE THE FOLLOWING ANNOTATIONS AND RECEIVE FEEDBACK ON THEM. <i class="fa fa-exclamation"> </i></a>';?>
  </div>

  <div class="menu-frame grid-container" id="my-menu-frame">

<div class="current-claim-div font-weight-bold grid-item">

<button id= 'go-back' class="btn btn-primary fa fa-arrow-circle-left fa-lg pull-left"></button>
<button id= 'go-forward' class=" btn btn-primary fa fa-lg fa-arrow-circle-right pull-left" disabled></button>
<p class="label-current-claim center"> <button type="button" class="btn btn-sm btn-info small h-5 fa fa-info rounded-circle rounded-sm" data-toggle="popover" title="Claim" data-content=	" The given claim is a one-sentence factoid generated by annotators based on Wikipedia in a previous annotation task. If a claim is not verifiable (e.g. due to being subjective or not being grammatical) you can report the claim using the appropriate button.)  "></button> CURRENT CLAIM:</p>
<p id="current-claim" class="text-center text-danger" > </p>
</div>

<div class="grid-item">


</div>

<div class="annotated-evidence-div-sets grid-item">
<button type="button" class="btn btn-sm btn-info small h-5 fa fa-info rounded-circle rounded-sm pull-left button-responsive-info" data-toggle="popover" data-html="true" title="Evidence Annotation" data-content=" Click on relevant information in either text, table, or lists anywhere on wikipedia to be added as evidence. Read section 3 of the guidelines in detail and look at the provided examples! <br> <ul>
<li> You are able to find three evidence sets here. Their purpose is to allow you to create multiple sets of evidence. This is needed for the situation in which you collected enough evidence to either support or refute a claim but found new evidence that is able to support or refute the claim independently from your already annotated evidence.
<li> In case the highlighted sentence/cells/items additionally requires knowledge of the article's title, section header, or table caption, the part has to be explicitly highlighted.
<li> You can navigate freely on any page of this Wikipedia, however, for navigation you are only allowed to use either the available Wikipedia search field, page search field, or hyperlinks in articles. <b> Apart from the browser's back-button do not use your browser navigation tools (e.g. CTRL + F) for navigation <b>.
</ul>"></button>
<button id="set1" class="evidence-set btn btn-sm"> Set 1:  <span class="fa-stack">
<i class="fa fa-circle fa-stack-2x"></i>
<i class="fa fa-file-text fa-stack-1x fa-inverse"></i>
</span> </button>
&ensp;&ensp;
<button  id="set2" class="evidence-set btn btn-sm"> Set 2:<span class="fa-stack">
<i class="fa fa-circle fa-stack-2x"></i>
<i class="fa fa-file-text fa-stack-1x fa-inverse"></i>
</span></button>
&ensp;&ensp;
<button  id="set3" class="evidence-set btn btn-sm"> Set 3:
<span class="fa-stack">
<i class="fa fa-circle fa-stack-2x"></i>
<i class="fa fa-file-text fa-stack-1x fa-inverse"></i>
</span></button>

<div class="annotated-evidence-div">
</div>
</div>


<div class="evidence-annotation-verdict grid-item">

<button type="button" class="btn btn-sm btn-info small h-5 fa fa-info rounded-circle button-responsive-info"  data-html="true"  data-toggle="popover" title="Expected Verification Challenges" data-placement="left" data-content=	"We are interested in gaining more insights into the main challenge you have had for annotating the given claim.
<ul>
<li><b>Search terms not in claim</b>  Finding relevant search terms to pages with required evidence to verify a given claim goes beyond searching for terms located in the claim itself.</li>
<li><b>Multi-hop Reasoning</b>  Multi-hop reasoning will be a challenge for verifying that claim, i.e. several documents will be required for verification. </li>
<li><b>Numerical reasoning</b> Numerical reasoning required to verify the claim will be a challenge, i.e. reasoning that involves numbers or arithmetic calculations. </li>
<li><b>Combining Tables/Lists and Text </b> Combining list(s)/table(s) with information from text will be the the main challenge, i.e. when the Text provides important context to Tables/List to be understood </li>
<li><b>Entity Disambiguation</b> Disambiguating an entity is the expected main challenge for verifying a given claim. </li>
<li><b>Other</b> If none of the above challenges can be identified. </li>
"></button>
<select id="evidence-annotation-challenge-selector" class="selectpicker">
  <option value="Select challenge" selected disabled hidden>Select challenge</option>
   <option value="Multi-hop Reasoning" data-content='<span data-toggle="tooltip" data-placement="right" title="Multi-hop reasoning will be a challenge for verifying that claim, i.e. several documents will be required for verification.">Multi-hop Reasoning</span>'>Multi-hop Reasoning</option>
   <option value="Numerical Reasoning" data-content='<span data-toggle="tooltip" data-placement="right" title=" Numerical reasoning required to verify the claim will be a challenge, i.e. reasoning that involves numbers or arithmetic calculations.">Numerical Reasoning</span>'>Numerical Reasoning</option>
   <option value="Combining Tables/Lists and Text" data-content='<span data-toggle="tooltip" data-placement="right" title="Combining list(s)/table(s) with information from text will be the the main challenge, i.e. when the Text provides important context to Tables/List to be understood.">Combining Tables/Lists and Text</span>'>Combining Tables/Lists and Text</option>
    <option value="Entity Disambiguation" data-content='<span data-toggle="tooltip" data-placement="right" title="Disambiguating an entity is the main challenge for verifying a given claim.">Entity Disambiguation</span>'>Entity Disambiguation</option>
   <option value="Search terms not in claim" data-content='<span data-toggle="tooltip" data-placement="right" title=" Finding relevant search terms to pages with required evidence to verify a given claim goes beyond searching for terms located in the claim itself.">Search terms not in claim</span>'>Search terms not in claim</option>
 <option value="Other" data-content='<span data-toggle="tooltip" data-placement="right" title="If none of the above challenges can be identified.">Other'>Other</option>
</select>
&nbsp;
&nbsp;
&nbsp;
&nbsp;
<button type="button" title="Verdict" class="btn btn-sm btn-info small h-5 fa fa-info rounded-circle rounded-sm button-responsive-info" data-toggle="popover" data-html="true" data-content=	"
<ul>
<li> Ask yourself: If I was given only the selected sentences, table cells, and list items, do I have strong enough reason to believe the claim is supported or strong enough reason to believe the claim is refuted. If I’m not certain, what additional information do I have to add to reach this conclusion and can I find it on Wikipedia? If I cannot find the required evidence, then the claim should be marked as NotEnoughInformation.
<li> If a claim is marked as NotEnoughInformation please still submit the evidence found in the process of reaching this verdict!
</ul>
"></button>

<select id="evidence-annotation-verdict-selector" class="selectpicker">
  <option value="Select verdict" selected disabled hidden>Select verdict</option>
  <option value="Supported" data-content='<span data-toggle="tooltip" data-placement="right">Supported</span>'>Supported</option>
  <option value="Refuted" data-content='<span data-toggle="tooltip" data-placement="right">Refuted</span>'>Refuted</option>
  <option value="Not enough Information" data-content='<span data-toggle="tooltip" data-placement="right">Not enough Information</span>'>Not enough Information</option>
</select>
<br>
<br>
<br>
<br>
<div class="input-group-append evidence-annotation-submit">
<button class="my_popup fa fa-check btn btn-success button-responsive">Submit Annotation </button>
&nbsp;
&nbsp;
&nbsp;
&nbsp;
<button type="button" id='report-button' class="btn btn-warning fa fa-exclamation-triangle button-responsive" <?php if ($_SESSION['finished_calibration'] !=2) echo 'disabled';?>>Report</button>
<button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"  <?php if ($_SESSION['finished_calibration'] !=2) echo 'disabled';?>>
  <span class="sr-only">Toggle Dropdown</span>
</button>
  <div class="dropdown-menu">
  <a class="dropdown-item report-item"  value="NEI">Cannot be verified using any publicly available information </a>
  <a class="dropdown-item report-item" value="NEI">Does not meet the claim generation guidelines</a>
  <a class="dropdown-item report-item"  value="supported">Ungrammatical, spelling mistakes, typographical errors</a>
  <a class="dropdown-item report-item"  value="supported">Required evidence is not displayed correctly <br> (e.g. tokenization errors, wrongly formatted tables)</a>
  <input id= 'report-note' class="dropdown-item" placeholder='Enter Note...'>
</div>
</div>
</div>
</div>

<section id="popup" style="display:none">
  <h5 id="current-claim-confirmation" class="text-center text-danger font-weight-bold"> </h5>
  <hr style="height:5px;background-color: #333;">
  <h5 id="verdict-confirmation">Verdict:  <h5>
  <h5 id="challenge-confirmation">Main Challenge:  <h5>
  <hr style="height:5px;background-color: #333;">
  <h5 class="text-center"> Evidence </h5>
  <div id="evidence-confirmation" style="border-style:solid;background-color:#D3D3D3">
  </div>
  <div style="padding:20px" class="text-center">
  <button class="evidence-annotation-submit-button fa fa-check btn btn-success"> Submit Annotation </button>
  <button class="adjust-evidence-selection fa fa-minus-circle btn btn-warning button-responsive"> Adjust Annotation </button>
</div>
</section>

</body>
</html>
